name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "gen/**"
      - "package.json"
  pull_request:
    branches:
      - main
    paths:
      - "package.json"
      - "src**"
      - "gen/**"
      - "test/**"
      - ".github/workflows/ci.yml"

jobs:
  check:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.3
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Typecheck
        uses: gozala/typescript-error-reporter-action@v1.0.8
        with:
          project: ./tsconfig.json

  test-node:
    name: Test Node
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 16
        os:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.3
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Test
        run: pnpm run test:node
  test-web:
    name: Test Web
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.3
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install
        run: pnpm install

      - name: Test
        run: yarn run test:web
